Update auto-commit.yml

diff --git a/.github/workflows/auto-commit.yml b/.github/workflows/auto-commit.yml
--- a/.github/workflows/auto-commit.yml
+++ b/.github/workflows/auto-commit.yml
@@ -11,7 +11,14 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
+
+    - name: Check out the master branch
+      run: git checkout master
+
+    - name: Pull latest changes
+      run: |
+        git pull || { echo 'Pull failed'; exit 1; }
 
     - name: Make changes
       run: |
@@ -24,20 +31,6 @@ jobs:
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git add .
         git commit -m "Automated commit for $(date +'%Y-%m-%d')"
-
-    - name: Check out the master branch
-      run: git checkout master
-      
-    - name: Pull latest changes
-      run: |
-        git pull --rebase
-
-    - name: Check for unmerged paths
-      run: |
-        if git ls-files -u | grep "."; then
-          echo "Conflict detected, please resolve conflicts before pushing."
-          exit 1
-        fi
 
     - name: Push changes
       uses: ad-m/github-push-action@v0.6.0
